# Generated by Django 2.1.2 on 2018-11-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.IntegerField(blank=True, verbose_name='생년월일6자리'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, '남자'), (1, '여자')], verbose_name='성별'),
        ),
    ]
