# Generated by Django 2.1.2 on 2018-11-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181101_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.IntegerField(blank=True, null=True, verbose_name='생년월일6자리'),
        ),
    ]
