# Generated by Django 2.1.2 on 2018-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181101_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, '남자'), (1, '여자')], null=True, verbose_name='성별'),
        ),
    ]
