# Generated by Django 2.1.2 on 2018-11-01 14:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181101_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skin_color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(blank=True, choices=[(1, '밝은'), (2, '중간'), (3, '어두운'), (4, '웜톤'), (5, '쿨톤'), (6, '모름')], null=True), blank=True, null=True, size=None, verbose_name='피부톤'),
        ),
    ]
