# Generated by Django 2.1.2 on 2018-11-02 09:36

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20181102_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('1', '밝은'), ('2', '중간'), ('3', '어두운'), ('4', '웜톤'), ('5', '쿨톤'), ('6', '모름')], max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='피부톤'),
        ),
    ]
