# Generated by Django 2.1.2 on 2018-11-06 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='영문/숫자만 입력해주세요.', regex='^[a-zA-Z0-9]+$')], verbose_name='아이디'),
        ),
    ]
