# Generated by Django 2.1.2 on 2018-11-06 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20181106_1613'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='영문/숫자만 입력해주세요.', regex='^[a-zA-Z0-9]+$')], verbose_name='username'),
        ),
    ]
