# Generated by Django 2.1.2 on 2018-11-08 01:55

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20181106_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',), 'verbose_name': '사용자 정보', 'verbose_name_plural': '사용자 정보'},
        ),
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
