# Generated by Django 2.1.2 on 2018-11-08 05:51

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20181108_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
        migrations.AlterField(
            model_name='user',
            name='face_point',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='특징'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_makeup',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='관심있는 메이크업'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skin_color',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='피부톤'),
        ),
    ]
